#!/usr/bin/env python3
"""Generate curated example pages from metadata and unchanged repository YAML."""

import json
from pathlib import Path
import re
import sys

try:
    import tomllib
except ModuleNotFoundError:
    sys.exit("error: website example generation requires Python 3.11 or newer")

WEBSITE = Path(__file__).resolve().parents[1]
ROOT = WEBSITE.parent
OUTPUT = WEBSITE / "content/examples"
MARKER = "<!-- Generated by website/scripts/generate_examples.py; do not edit. -->"
DOC_LABELS = {
    "getting-started": "Getting started",
    "providers": "Model providers",
    "evaluation": "Evaluation",
    "built-in-tools": "Built-in tools",
    "yaml-reference": "YAML reference",
    "concepts": "Core concepts",
}


def repository_file(value, prefix):
    """Require local catalog references to exist inside the intended source tree."""
    path = ROOT / value
    if not value.startswith(prefix) or not path.resolve().is_relative_to((ROOT / prefix).resolve()) or not path.is_file():
        raise ValueError(f"Missing or invalid recipe source: {value}")
    return path


def generate():
    """Validate all metadata before replacing only files owned by this generator."""
    catalog = tomllib.loads((WEBSITE / "catalog/recipes.toml").read_text(encoding="utf-8"))
    config = tomllib.loads((WEBSITE / "config.toml").read_text(encoding="utf-8"))
    github = config["extra"]["github"].rstrip("/")
    pages = {}
    for index, recipe in enumerate(catalog["recipes"], start=1):
        slug = recipe["slug"]
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug) or slug in pages:
            raise ValueError(f"Invalid or duplicate recipe slug: {slug}")
        source = repository_file(recipe["source"], "examples/yaml/")
        yaml = source.read_text(encoding="utf-8")
        supporting = recipe.get("supporting", [])
        for path in supporting:
            repository_file(path, "examples/yaml/")
        suite = recipe.get("eval")
        if suite:
            repository_file(suite, "examples/eval/mocked/")
        for doc in recipe["docs"]:
            if doc not in DOC_LABELS or not (WEBSITE / "content/docs" / f"{doc}.md").is_file():
                raise ValueError(f"Missing recipe documentation: {doc}")
        # JSON strings and arrays are valid TOML values and safely quote frontmatter.
        frontmatter = ["+++", f'title = {json.dumps(recipe["title"])}',
                       f'description = {json.dumps(recipe["summary"])}',
                       'template = "example.html"', f'slug = "{slug}"',
                       f"weight = {index}", "[extra]"]
        for key in ("goal", "features", "setup", "source"):
            frontmatter.append(f"{key} = {json.dumps(recipe[key])}")
        frontmatter += [f'mocked_eval = {str(bool(suite)).lower()}', "+++", "", MARKER, ""]
        content = ["## What you will build", "", recipe["summary"], "", "## Before you run", "",
                   "Use a full [repository checkout](" + github + ") and run the commands from its root. "
                   "Install the Rust toolchain required by the repository; Cargo builds the CLI on first use.", ""]
        content += [f"- {item}" for item in recipe["prerequisites"]]
        content += ["", "## How it works", ""]
        content += [f"{number}. {item}" for number, item in enumerate(recipe["flow"], start=1)]
        content += ["", "## Run the agent", "", "```sh",
                    f'cargo run -p ai-agents-cli -- run {recipe["source"]}', "```", ""]
        if supporting:
            content += ["Keep these supporting files alongside the parent YAML:", ""]
            content += [f"- [{path}]({github}/blob/main/{path})" for path in supporting]
            content.append("")
        content += ["## Check the behavior", ""]
        if suite:
            content += ["This existing mocked suite supplies model responses and checks runtime behavior without provider credentials. "
                        "It demonstrates the assertions in the suite; it does not measure live model quality.", "", "```sh",
                        "cargo run -p ai-agents-cli -- eval \\", f"  --scenarios {suite} \\",
                        f"  --output target/eval/recipes/{slug}", "```", "",
                        f"[Read the mocked suite]({github}/blob/main/{suite}) · "
                        "[Understand evaluation reports](@/docs/evaluation.md)", ""]
        else:
            content += ["This local-provider example has no dedicated mocked suite in the catalog. "
                        "Use the local server to check its actual response, or follow the "
                        "[first conversation example](@/examples/recipe-first-chat.md) for a credential-free runtime smoke test. "
                        "A mocked test does not verify your local Ollama installation.", ""]
        content += ["## Make it yours", ""]
        content += [f"- {item}" for item in recipe["customize"]]
        content += ["", "## Original YAML", "",
                    f'[View the source file]({github}/blob/main/{recipe["source"]}). '
                    "The following content is copied directly from that file at site build time.", ""]
        # A longer fence keeps an embedded Markdown fence in YAML comments literal.
        fence = "`" * max(3, max((len(match.group()) + 1 for match in re.finditer(r"`+", yaml)), default=3))
        content += [fence + "yaml", yaml.rstrip("\n"), fence, "", "## Keep exploring", ""]
        content += [f"- [{DOC_LABELS[doc]}](@/docs/{doc}.md)" for doc in recipe["docs"]]
        content += ["- [All examples](@/examples/_index.md)", ""]
        pages[slug] = "\n".join(frontmatter + content)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    expected = {f"recipe-{slug}.md" for slug in pages}
    for old in OUTPUT.glob("recipe-*.md"):
        if old.name not in expected and MARKER in old.read_text(encoding="utf-8"):
            old.unlink()
    for slug, content in pages.items():
        destination = OUTPUT / f"recipe-{slug}.md"
        if destination.exists() and MARKER not in destination.read_text(encoding="utf-8"):
            raise ValueError(f"Refusing to overwrite non-generated page: {destination}")
        destination.write_text(content, encoding="utf-8")
    print(f"Generated {len(pages)} source-backed example pages")


if __name__ == "__main__":
    try:
        generate()
    except (KeyError, ValueError, OSError) as error:
        sys.exit(f"error: cannot generate website examples: {error}")
